Algorithm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WebAlgorithm.urls'))
]

WebAlgorithm/models.py
from django.db import models
from django.contrib.auth.models import User
import django.utils.timezone as tm
import random
import os
from django.utils.text import slugify

def week_delta():
    return tm.now().date() + tm.timedelta(weeks=1)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, blank=True, verbose_name='Номер телефона')
    age = models.PositiveSmallIntegerField(blank=True, verbose_name='Возраст', default=1)
    user_img = models.ImageField(upload_to='user_img/', verbose_name='Фото', default='user_img/default_user.png')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_teacher = models.BooleanField(default=False, verbose_name='Учитель?')

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name


class Course(models.Model):
    name = models.CharField(max_length=70, verbose_name="Название курса")
    course_img = models.ImageField(upload_to='course_img/', verbose_name='Превью', default='course_img/default_course.jpg')
    course_description = models.TextField(max_length=250, verbose_name='Описание', blank=True)
    course_teacher = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Учитель')
    update_time = models.DateTimeField(auto_now=True)
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    url = models.SlugField(max_length=100, unique=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.url = slugify(self.name)
        super(Course, self).save(*args, **kwargs)


class CourseList(models.Model):
    user_id = models.ForeignKey(Profile, on_delete=models.CASCADE)
    course_id = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.user_id.user.first_name + ' ' + self.course_id.name


class Lesson(models.Model):
    lesson_title = models.CharField(max_length=100, verbose_name='Тема урока')
    description = models.TextField(max_length=10000, verbose_name='Описание урока', blank=True)
    attached_files = models.FileField(upload_to='attached_files/', verbose_name='Прикрепленные файлы', blank=True)
    fk_course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Урок курса')
    url = models.SlugField(unique=True)
    is_hidden = models.BooleanField(default=False, verbose_name='Скрыть?')
    update_time = models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    HomeTask_title = models.CharField(max_length=200, verbose_name='Тема домашнего задания', blank=True, default='New', null=True)
    HomeTask_description = models.TextField(max_length=100000, verbose_name='Описание задания', blank=True, default='New', null=True)
    deadline_time = models.DateField(verbose_name='Дата сдачи', default=week_delta)
    is_hometask = models.BooleanField(verbose_name='Не прекреплять домашнее задание', default=False)

    def __str__(self):
        return 'Курс:   ' + self.fk_course.name + '   <<I I>>   Урок:   ' + self.lesson_title

    def save(self, *args, **kwargs):
        self.url = slugify(self.lesson_title[0:15]+'-'+self.fk_course.name)
        super(Lesson, self).save(*args, **kwargs)

    def filename(self):
        return os.path.basename(self.attached_files.name)


class HomeTask(models.Model):
    fk_lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name='Д/з урока --')
    fk_user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Для ученика --')
    HomeTask_attached_files = models.FileField(upload_to=f'home_task/', verbose_name='Прикрепленные файлы', blank=True)
    update_time = models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')
    comment = models.TextField(max_length=100000, blank=True, verbose_name='Комментарий преподавателя')
    is_passed = models.BooleanField(default=False, verbose_name="Сдано?")
    mark = models.IntegerField(verbose_name='Оценка', choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'),
                                                               (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], blank=None, default=0)

    def __str__(self):
        return self.fk_lesson.HomeTask_title + ' -> ' + self.fk_lesson.lesson_title + ' -> ' + self.fk_user.user.first_name


class CommentHomeTask(models.Model):
    fk_user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Кто отправил')
    fk_home_task = models.ForeignKey(HomeTask, on_delete=models.CASCADE, verbose_name='Чье дз')
    comment_text = models.TextField(max_length=1000, verbose_name='Текст комментрия')
    creation_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fk_user.user.first_name + self.fk_user.user.last_name + '--->>>' \
               + self.fk_home_task.fk_user.user.first_name + self.fk_home_task.fk_user.user.last_name

templates/Add_Lesson.html
{% extends 'basic_template.html' %}
{% block title %}Создание урока{% endblock %}
{% load static %}
{% block content %}

    <div class="content_box">
{% if user.profile.user_id == course_cur.course_teacher.user.profile.user_id and user.profile.is_teacher %}

    <form method="post" class="mt-5" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="title_edit_block d-flex justify-content-center">
            <span class="title-nav title_block_ h1 font-weight-bold ">Создание урока</span>
        </div>

<div class="mt-4 mb-5 w-75 ml-4">
        <div class="mb-3 h3 title-nav title_block_ mt-2">{{ Lesson_form.lesson_title.label }}:</div>
        <div class="ml-3 mt-3">{{ Lesson_form.lesson_title }}</div>

        <div class="mb-3 h3 title-nav title_block_  mt-4">{{ Lesson_form.description.label }}:</div>
        <div class="ml-3 mt-3">{{ Lesson_form.description }}</div>

        <div class="mb-3 h3 title-nav title_block_ mt-4">{{ Lesson_form.attached_files.label }}:</div>
        <div class="ml-3 mt-3">{{ Lesson_form.attached_files }}</div>
        <div class="custom-control custom-checkbox mt-4 mb-5">
          {{ Lesson_form.is_hidden }}
          <label class="custom-control-label " for="id_is_hidden">Скрыть урок</label>
        </div>

        <div class="mb-3 h3 title-nav title_block_ font-weight-bold mt-4 url_hide">{{ Lesson_form.url.label }}:
        {{ Lesson_form.url }}
        {{ Lesson_form.errors }}</div>


    </div>

        <div class="title_edit_block d-flex justify-content-center">
            <span class="title-nav title_block_ h1 font-weight-bold ">Добавить домашнее задание</span>
        </div>

<div class="mt-4 mb-5 w-75 ml-4">
        <div class="mb-3 h3 title-nav title_block_  mt-3">{{ Lesson_form.HomeTask_title.label }}:</div>
        <div class="ml-3 mt-3">{{ Lesson_form.HomeTask_title }}</div>

        <div class="mb-3 h3 title-nav title_block_  mt-3">{{ Lesson_form.HomeTask_description.label }}:</div>
        <div class="ml-3 mt-3">{{ Lesson_form.HomeTask_description }}</div>

        <div class="mb-3 h3 title-nav title_block_  mt-3">{{ Lesson_form.deadline_time.label }}:</div>
        <div class="ml-3 mt-3 mb-5" style="max-width: 300px;">{{ Lesson_form.deadline_time }}</div>
                <div class="custom-control custom-checkbox mt-4 mb-5">
              {{ Lesson_form.is_hometask }}
              <label class="custom-control-label" for="id_is_hometask">Не преереплять домашнее задание</label>
            </div>
        <p class="mt-3">{{ errors }}</p>
    <div class="mb-5 ml-1 mr-1">
        <button type="submit" class="mb-5 ml-3 btn btn-lg btn-outline-success" style="min-width:190px; max-width: 400px">Применить</button>
        <a href="../{{course_cur.url}}" class="mb-5 ml-3 btn btn-lg btn-outline-warning" style="min-width:190px; max-width: 400px">Вернуться не добавляя</a>
    </div>
 <div class="url_hide">{{ Lesson_form.fk_course }}</div>
</div>


    </form>
</div>



{% endif %}
{% endblock %}

templates/Calendar.html
{% extends 'basic_template.html' %}
{% block title %}Профиль {{ user.first_name }} {{ user.last_name }}{% endblock %}
{% load static %}
{% block content %}
    <div class="content_box mb-5">
        <div class="profile_block mr-0 mt-5 mb-5 ml-3 position-relative">
            <div class="img_block d-inline-block position-relative">
                <img class="img-thumbnail profile_img"  style="width: 10rem; border-color: #183E87;" src="{% static user.profile.user_img %}" alt='ICON'>
                <form method="POST" enctype="multipart/form-data" class="form_par" id="form_pic_id">
                    {% csrf_token %}
                    {{ form_pic }}
                </form>
            </div>

            <div class="profile_title d-inline-block position-absolute">
                <div class="profile_name a_ml3">
                    <span class="h2 prof_span">{{user.first_name}}</span>
                    <span class="h2 prof_span">{{user.last_name}}</span>
                    <p class="text-muted pt-2 pl-1 h5 font-weight-light">{% if user.profile.is_teacher %} Учитель {% else %} Ученик {% endif %} </p>
                </div>
            </div>
        </div>
334`
        <div class="calendar_block">
        <div class="d-flex justify-content-center text-center h1 text-muted h1_auto">{{ month }} {{ year }}</div>
        <div class="sep_line" style="background: #183E87;"></div>
         <div class="row row-cols-7 mt-5">
            {% for week_day, day, list_home_tasks, lessons_list  in week_days %}
              <div class="card mb-2">
{#                <img src="{% static 'icons/ReturnIcon.png' %}" class="card-img-top w-25" alt="">#}
                <div class="card-body overflow-hidden pt-1 pr-2 pl-2 pb-5{% if day == number_day_today %} bg-today{% elif day < number_day_today %} bg-today-pass text-muted {% elif day > number_day_today %} text-muted {% endif %}">
                  <span class="card-title "><span class="font-weight-bold">{{ day }}</span> <span class="font-weight-light float-right">{{week_day}}</span></span>
                  <br><span class="card-text pt-3">
                    <div class="mt-2"></div>
                  {% for lesson in lessons_list %}
                      {% if not lesson.is_hidden and not lesson.is_hometask%}
                        <a class="font-weight-normal" href="/course/{{ lesson.fk_course.url }}/{{ lesson.url }}">{{ lesson.fk_course|slice:":10" }}: {{ lesson.lesson_title|slice:":10" }}</a>
                          {% for home_task in list_home_tasks %}
                              {% if home_task.fk_lesson.id == lesson.id %}
                                  {% if home_task.HomeTask_attached_files%}
                                      {% if home_task.is_passed %}
                                        <img src="{% static 'icons/Ok.png' %}" alt="" style="max-height: 12px; max-width: 12px; margin-bottom: 5px">
                                      {% else %}
                                          <img src="{% static 'icons/So.png' %}" alt="" style="max-height: 12px; max-width: 12px; margin-bottom: 5px">
                                      {% endif %}
                                  {% endif %}
                              {% endif %}
                          {% endfor %}
                          <hr class="m-0 p-0">
                      {% endif %}
                  {% endfor %}
                  </span>
                  <p class="card-text"><small class="text-muted"></small></p>
                </div>
              </div>
{#                {{ day }}#}
            {% endfor %}
         </div>
        </div>


    </div>
{% endblock %}
{#<script>#}
{#    document.getElementById("file").onchange = function() {#}
{#    document.getElementById("form_pic_id").submit();};#}
{#</script>#}

templates/Check_HT.html
{% extends 'basic_template.html' %}
{% block title %}Курс {{course_cur.name}}{% endblock %}
{% load static %}
{% block content %}
<div class="content_box">
{% if user.profile.user_id == course_cur.course_teacher.user.profile.user_id and user.profile.is_teacher %}

    <form method="post" class="mt-5 mb-5" enctype="multipart/form-data">
        {% csrf_token %}
        <a href="../{{ lesson.url }}" class="position-absolute mt-2">
            <img src="{% static 'icons/ReturnIcon.png' %}" alt="" style="max-width: 44px; max-height: 44px;">
        </a>
        <div class="title_edit_block mb-0 d-flex justify-content-center">
            <span class="title-nav title_block_ h1  ">{{ cur_ht.fk_user.user.first_name }} {{ cur_ht.fk_user.user.last_name }}</span>
        </div>
        <div class="title_edit_block d-flex justify-content-center mt-0">
            <span class="font-italic font-weight-light text-muted">Курс - {{ course_cur.name }}</span>
        </div>
        <div class="title_edit_block d-flex justify-content-center">
            <span class="font-italic font-weight-light text-muted">Урок - {{ lesson.lesson_title }}</span>
        </div>

        <div class="">
            <div class=" w-100 mt-0 mb-0">
                    <span class="h2 title-nav   mb-0 title_block_ ">Задание:</span>
            </div>
            <div class="ml-3 mt-2">
                {{ lesson.HomeTask_description }}
            </div>
        </div>

            <div class=" w-100">
                <div class="w-100 mt-5 mb-2">
                <div class=" w-100 mt-0 mb-0">
                    <span class="h2 title-nav   mb-0 title_block_ ">Прикрепленные файлы:</span>
                </div>
                    <div class="text-center mt-3 d-flex justify-content-center">
    {% if cur_ht.HomeTask_attached_files %}
                            <div class="card text-white bg-secondary mb-3 " style="max-width: 18rem;">
                                  <div class="card-header h5" style="color: white;">
                                      Файл <br> <span class="font-weight-lighter font-italic">{{ cur_ht.update_time }}</span>
                                  </div>
                                  <div class="card-body">
                                    <h5 class="card-title font-weight-lighter">{{cur_ht.HomeTask_attached_files.name }}</h5>
                                      <a href="{{ cur_ht.HomeTask_attached_files.url }}" class="btn btn-outline-warning2 mt-2" download>Скачать</a>
                                  </div>
                             </div>
                                    {% else %}
                                <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                                    <div class="card-header h5">
                                          Файл не приложен</span>
                                      </div>
                                      <div class="card-body">

                                      </div>
                                 </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                     <div class="w-100 mb-2 mt-5">
                        <div class="w-100 mt-2 mb-1 ">
                                            <div class="w-100 mt-0">
                            <span class="h2 title-nav   mt-5 mb-1 title_block_">Отметить как приянтое:</span>
                                            </div>
                            <div class="custom-control custom-checkbox mt-3 mb-1 ml-3">
                              {{ home_task_form.is_passed }}
                              <label class="custom-control-label  " for="id_is_passed">Зачтено!</label>
                            </div>
                         </div>
                     </div>
                     <div class="w-100 mb-2 mt-5">
                        <div class="w-100 mt-2 mb-1 ">
                                            <div class="w-100 mt-0">
                            <span class="h2 title-nav   mt-5 mb-1 title_block_">Оценка:</span>
                                            </div>
                            <div class="custom-control mt-2" style="width: 30vw;">
                              {{ home_task_form.mark }}
                            </div>
                         </div>
                     </div>
<div class="mt-1 mb-0 d-flex justify-content-center">
    <button type="submit" class="btn btn-outline-success2 mb-5 mt-5 btn-lg ml-0 ">Применить</button>

 </div>

    </form>
    <div class="comment_block">
    <a href="" name="comment"></a>
    <div class="mb-2">
        <span class="title-nav h2   title_block_">Комментарии к Д\З:</span><br>
    <ul class="list-group mt-3 ml-3" style='border-radius: 20px'>
    {% for comment in comments %}
        <li class="list-group-item p-0" style="border-radius: 25px">
            <div class="media ml-4 mt-3 mb-3">
              <img src="{% static comment.fk_user.user.profile.user_img%} " class="mr-4 img-thumbnail" alt="..."  style="max-width: 64px; max-height: 64px; {% if comment.fk_user.user.id == course_cur.course_teacher.user.id %} border-color: #09af00; {% else %} border-color: #183E87; {% endif %}">
              <div class="media-body overflow-auto">
                <span class="mt-0 h5">{{ comment.fk_user.user.first_name }} {{ comment.fk_user.user.last_name}}</span>
                   {% if comment.fk_user.user.id == course_cur.course_teacher.user.id %}
                        <span class="ml-1 text-muted font-italic">(Преподаватель)</span>
                    {% endif %}
              {% if comment.fk_user.user.id == user.id or course_cur.course_teacher.user.id == user.id %}
                <a href="../{{ lesson.url }}/DelComment/{{ comment.id }}" class="float-right mr-3 font-weight-light">
                    <img src="{% static 'icons/del.png' %}" alt="Удалить" style="max-height: 22px; max-width: 22px;">
                </a>
              {% endif %}
                  <br><span class="text-muted font-weight-light">{{ comment.creation_time }}</span>
                  <br>
                  <span class="">{{ comment.comment_text }}</span>
              </div>
            </div>
        </li>
    {% endfor %}
    </ul>
    </div>
        <div class="add_comment mt-4">
            <form method="post">
                {% csrf_token %}
                <div class="ml-3 h-25">{{ comment_form.comment_text }}</div>

                <div class="url_hide position-absolute">{{ comment_form.fk_user }} {{ comment_form.fk_home_task }}</div>
                <div class="ml-3 d-flex justify-content-start">
                    <button class="btn-lg btn btn-success2 mt-3 mb-5" type="submit">Добавить комментарий</button>
                </div>
            </form>
        </div>

    </div>
</div>





{{ errors }}

{% endif %}
{% endblock %}

templates/Course.html
{% extends 'basic_template.html' %}
{% block title %}Курс {{course_cur.name}}{% endblock %}
{% load static %}
{% block content %}
{##}
{#    <div class="course_title mt-5">#}
{#        <img src="{% static course_cur.course_img %}" class="img-thumbnail w-25" alt="Img">#}
{#        <div class="title_block font-weight-bolder d-inline-block position-absolute ml-4"><h3 class="card-title">{{ course_cur.name }}</h3></div>#}
{#        <div class="description_block"><p class="card-text">{{ course_cur.course_description }}</p></div>#}
{#    </div>#}
{% for record in course_list %}
    {% if record.user_id.user.profile.user_id == user.profile.user_id%}
        {% if record.course_id.id == course_cur.id %}
            <div class="card border-0 block_card d-flex justify-content-center align-items-center align-self-center" style="border-radius: 0">
            <div class="card w-100 text-white border-0 card_100vh" style="border-radius: 0; background: url({% static course_cur.course_img %}) 50%/cover no-repeat;">
                  <div class="card-img-overlay pt-5 card_bloack_text d-flex justify-content-center" style="">
                      <div class="a_mt3 text_block">
                         <h1 class="card-title mb-0 h1 a_mt3" style="color: white;">{{ course_cur.name }}
                             {% if course_cur.course_teacher.user_id == user.profile.user_id and user.profile.is_teacher%}
                                 <a href="EditPage" ><img class="mb-4" src="{% static 'icons/Edit.png' %}" alt="" style="max-width: 16px; max-height: 16px; position:absolute; margin-left: 10px;"></a>
                          {% endif %}
                          </h1>
                         <p class="card-text text-muted mt-2">{{ course_cur.update_time }}</p>
                          <div class="sep_line"></div>
                         <p class="card-text mt-5 font-weight-light h-25">{{ course_cur.course_description }}</p>

                          <p class="text-muted a_mt3">Преподаватель курса: {{ course_cur.course_teacher.user.last_name }} {{ course_cur.course_teacher.user.first_name }} </p>
{#                          <p class="text-warning">Ваш Преподаватель: {{ course_cur.course_teacher.user.last_name }} {{ course_cur.course_teacher.user.first_name }} </p>#}
                      </div>

                  </div>
            </div>
        </div>

<div class="content_box mb-5">
    <div class="d-flex justify-content-center align-items-center text-center h2 mt-5 title-nav"><span class="title_block_">Уроки курса:</span></div>
    <div class="lessons_block mt-5">
    
    <ul class="list-group">
        {% for i in lessons %}
            {% if i.fk_course.id == course_cur.id %}
                {% if not i.is_hidden or course_cur.course_teacher.user.profile.user_id == user.profile.user_id%}

                      <li class="list-group-item card_small">
                          <span class="font-weight-bold item_title">{{ i.lesson_title|slice:":60" }}</span>
                          <a href="{{ i.url }}" class="float-right btn btn-outline-success2 title-nav item_btn"><span class="btn_size_">Перейти</span></a>
                              {% if course_cur.course_teacher.user.profile.user_id == user.profile.user_id %}
                                <a href="{{ i.url }}/EditPage" class="float-right mr-3 font-weight-light font-italic edit_span item_edit">Редактировать</a>
                            {% endif %}

                          <br class="item_br">
                          <span class="text-muted text-light item_uptime">{{ i.update_time }}</span>
                             {% if i.is_hidden %}
                                 <img class="float-right mr-3 item_show" src="{% static 'icons/hide.png' %}" alt="Скрыт Урок" style="max-height: 20px; max-width: 20px;">
{#                                <span class="text-muted mr-3 float-right">Урок скрыт</span>#}
                             {% endif %}
                      </li>
                {% endif %}
            {% endif %}
        {% endfor %}
    {% if course_cur.course_teacher.user.profile.user_id == user.profile.user_id %}
        <a href="AddLesson">
        <li class="list-group-item" style="border-bottom-left-radius: 222px; border-bottom-right-radius: 222px; cursor: pointer;">
            <div class="add_block d-flex justify-content-center">
                <img src="{% static 'icons/add.png' %}" alt="ADD" style="max-width: 42px; max-height: 42px;">
            </div>
        </li>
        </a>
    {% endif %} 
      </ul>
    </div>
</div>
    {% endif %}
     {% endif %}
{% endfor %}
{% endblock %}
{#<script>#}
{#    document.getElementById("file").onchange = function() {#}
{#    document.getElementById("form_pic_id").submit();};#}
{#</script>#}

templates/Edit_Course.html
{% extends 'basic_template.html' %}
{% block title %}Курс {{course_cur.name}}{% endblock %}
{% load static %}
{% block content %}
<div class="content_box">
{% if user.profile.user_id == course_cur.course_teacher.user.profile.user_id and user.profile.is_teacher %}

    <form method="post" class="mt-5 mb-5" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="title_edit_block d-flex justify-content-center mb-4 ">
            <span class="title-nav title_block_ h1 font-weight-bold">Редактирование курса</span>
        </div>
        {% for field in FormEdit %}
            <div class="justify-content-center d-flex w-100">
                <div class="w-75 mt-3 mb-4 ">
                    <span class="h2 title-nav mt-4 mb-1 title_block_">{{ field.label }}:</span>
                    <br>
                    {{ field }}
                </div>

            </div>
        {% endfor %}
<div class="mt-3 mb-1 d-flex justify-content-center">
    <button type="submit" class="btn btn-outline-success mb-1 mt-5 btn-lg btn-block" style="max-width: 400px">Применить</button>
 </div>
<div class="mt-3 mb-1 d-flex justify-content-center">
    <a href="../{{course_cur.url}}" class="btn btn-outline-warning mb-5 btn-lg btn-block" style="max-width: 400px">Вернуться не изменяя</a>
 </div>
    </form>
</div>



{% endif %}
{% endblock %}

templates/Edit_Lesson.html
{% extends 'basic_template.html' %}
{% block title %}Урок {{lesson.lesson_title}}{% endblock %}
{% load static %}
{% block content %}

    <div class="content_box ">
{% if user.profile.user_id == course_cur.course_teacher.user.profile.user_id and user.profile.is_teacher %}

    <form method="post" class="mt-5" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="title_edit_block d-flex justify-content-center">
            <span class="title-nav title_block_ h1  font-weight-bold ">Редактирование урока</span>
        </div>

<div class="mt-4 mb-5 w-75 ml-4">
        <div class="mb-3 h3 title-nav  title_block_   mt-2">{{ Lesson_form.lesson_title.label }}:</div>
        <div class="ml-3 mt-3">{{ Lesson_form.lesson_title }}</div>

        <div class="mb-3 h3 title-nav   title_block_  mt-4">{{ Lesson_form.description.label }}:</div>
        <div class="ml-3 mt-3">{{ Lesson_form.description }}</div>

        <div class="mb-3 h3 title-nav  title_block_   mt-4">{{ Lesson_form.attached_files.label }}:</div>
        <div class="ml-3 mt-3">{{ Lesson_form.attached_files }}</div>

        <div class="mb-3 h3 title-nav title_block_    mt-4 url_hide position-absolute">{{ Lesson_form.url.label }}:
        {{ Lesson_form.url }}
        {{ Lesson_form.errors }}</div>

        <div class="custom-control custom-checkbox mt-4 mb-5">
          {{ Lesson_form.is_hidden }}
          <label class="custom-control-label   " for="id_is_hidden">Скрыть урок</label>
        </div>
    </div>

        <div class="title_edit_block d-flex justify-content-center mt-5 pt-5">
            <span class="title-nav title_block_ h1  font-weight-bold  ">Редактирование домашнего задания</span>
        </div>

<div class="mt-4 mb-5 w-75 ml-4">
        <div class="mb-3 h3 title-nav  title_block_   mt-3">{{ Lesson_form.HomeTask_title.label }}:</div>
        <div class="ml-3 mt-3">{{ Lesson_form.HomeTask_title }}</div>

        <div class="mb-3 h3 title-nav title_block_    mt-3">{{ Lesson_form.HomeTask_description.label }}:</div>
        <div class="ml-3 mt-3">{{ Lesson_form.HomeTask_description }}</div>

        <div class="mb-3 h3 title-nav  title_block_   mt-3">{{ Lesson_form.deadline_time.label }}:</div>
        <div class="ml-3 mt-3 mb-5" style="max-width: 400px">{{ Lesson_form.deadline_time }}</div>
            <div class="custom-control custom-checkbox mt-4 mb-5">
              {{ Lesson_form.is_hometask }}
              <label class="custom-control-label " for="id_is_hometask">Не прикреплять домашнее задание</label>
            </div>
        <p class="mt-3">{{ errors }}</p>
    <div class="mb-5">
        <button type="submit" class="mb-5 a_ml3 btn btn-lg btn-outline-success btn_size_" style="min-width: 160px">Применить</button>
        <a href="../{{lesson.url}}" class="mb-5 a_ml3 btn btn-lg btn-outline-warning btn_size_">Вернуться без применения</a>
    </div>

</div>


    </form>
</div>



{% endif %}
{% endblock %}